name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          command_timeout: 10m
          script: |
            set -e

            cd /var/www/be-pic-gwenza

            echo "Checking directory..."
            pwd
            ls -la

            echo "Load Node via NVM"
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm use 22.17.0

            echo "Check versions"
            node -v
            npm -v

            echo "Pull latest code"
            git pull origin main

            echo "Install dependencies"
            npm ci

            echo "Prisma generate"
            npx prisma generate

            echo "Prisma push"
            npx prisma db push --accept-data-loss

            echo "Restart PM2"
            pm2 reload ecosystem.config.cjs

            echo "Done 🚀"